apiVersion: 1

deleteDatasources:
  - name: Parametric
  - name: Sample_Data

datasources:
  - name: Sample_Data
    type: postgres
    typeName: PostgreSQL
    access: proxy
    url: postgres
    user: shoc
    database: sample_data
    basicAuth: false
    isDefault: true
    jsonData:
      postgresVersion: 903
      sslmode: disable
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: file-path
      tlsSkipVerify: true
    secureJsonData:
      password: JustKeepSwimming
    readOnly: false
	
  - name: Loki
    type: loki
	access: proxy
    url: http://loki:3100
    version: 1

